#! /bin/bash

# watch out for UNIX line endings
cd /var/services/homes/lechefforthis/Haussteuerung-config/Diskstation1
echo "pulling docker-compose.yml from git ..."
git pull
echo "pulling images if necessary ..."
docker-compose pull 
echo "updateing docker containers if necessary ..."
docker-compose up -d

